#!/usr/bin/env bash

set -e

BUILD_DIR=$(mktemp -d)

npm install
npm run build -- --dest $BUILD_DIR
git checkout gh-pages
git stash
git clean -f
cp -r $BUILD_DIR/* .
git add .
git commit -a
git checkout -
